### ISSUE TITLE
On ne peut plus créer de BDD depuis zéro

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#1042]
Si j'essaie de créer une nouvelle BDD depuis 0, lors du migrate, j'obtiens cette erreur :

```
python manage.py migrate
Running migrations for easy_thumbnails:
 - Migrating forwards to 0016_auto__add_thumbnaildimensions.
 > easy_thumbnails:0001_initial
 > easy_thumbnails:0002_filename_indexes
 > easy_thumbnails:0003_auto__add_storagenew
 > easy_thumbnails:0004_auto__add_field_source_storage_new__add_field_thumbnail_storage_new
 > easy_thumbnails:0005_storage_fks_null
 > easy_thumbnails:0006_copy_storage
 - Migration 'easy_thumbnails:0006_copy_storage' is marked for no-dry-run.
 > easy_thumbnails:0007_storagenew_fks_not_null
 > easy_thumbnails:0008_auto__del_field_source_storage__del_field_thumbnail_storage
 > easy_thumbnails:0009_auto__del_storage
 > easy_thumbnails:0010_rename_storage
 > easy_thumbnails:0011_auto__add_field_source_storage_hash__add_field_thumbnail_storage_hash
 > easy_thumbnails:0012_build_storage_hashes
 - Migration 'easy_thumbnails:0012_build_storage_hashes' is marked for no-dry-run.
 > easy_thumbnails:0013_auto__del_storage__del_field_source_storage__del_field_thumbnail_stora
 > easy_thumbnails:0014_auto__add_unique_source_name_storage_hash__add_unique_thumbnail_name_s
 > easy_thumbnails:0015_auto__del_unique_thumbnail_name_storage_hash__add_unique_thumbnail_sou
 > easy_thumbnails:0016_auto__add_thumbnaildimensions
 - Loading initial data for easy_thumbnails.
Installed 0 object(s) from 0 fixture(s)
Running migrations for munin:
 - Migrating forwards to 0001_initial.
 > munin:0001_initial
 - Loading initial data for munin.
Installed 0 object(s) from 0 fixture(s)
Running migrations for utils:
 - Migrating forwards to 0005_auto__add_index_categorysubcategory_is_main__add_index_alert_pubdate__.
 > utils:0001_initial
 > utils:0002_auto__add_field_alert_comment__add_field_alert_scope__chg_field_alert_
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 113, in run
    dry_run.run_migration(migration, database)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 192, in run_migration
    self._run_migration(migration)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 178, in _run_migration
    raise exceptions.FailedDryRun(migration, sys.exc_info())
south.exceptions.FailedDryRun:  ! Error found during dry run of '0002_auto__add_field_alert_comment__add_field_alert_scope__chg_field_alert_'! Aborting.
Traceback (most recent call last):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 175, in _run_migration
    migration_function()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/opt/zdsenv/ZesteDeSavoir/zds/utils/migrations/0002_auto__add_field_alert_comment__add_field_alert_scope__chg_field_alert_.py", line 22, in forwards
    keep_default=False)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/db/generic.py", line 411, in add_column
    sql = self.column_sql(table_name, name, field)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/db/generic.py", line 706, in column_sql
    default = field.get_db_prep_save(default, connection=self._get_connection())
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1236, in get_db_prep_save
    connection=connection)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 350, in get_db_prep_save
    prepared=False)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 607, in get_db_prep_value
    value = connection.ops.validate_autopk_value(value)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 336, in validate_autopk_value
    raise ValueError('The database backend does not accept 0 as a '
ValueError: The database backend does not accept 0 as a value for AutoField.
```

**Comment by Eskimon** [comment]
J'ai un fix testé sur une base mysql vide... Je pousse !!

**Comment by Eskimon** [comment]
Problème réglé !!
