### ISSUE TITLE
Erreur 500 sur la modification d'un utilisateur avec l'API

### ISSUE THREAD

**Issue by MrCirdo** [zestedesavoir/zds-site#2450]
Bonjour à tous,

Il y a un bug sur l'api.

Quand on veut modifier un utilisateur avec l'api avec le token, il nous renvoi une erreur 500. 
Voici la requête : 

```
PUT /api/membres/748/ HTTP/1.1
Host: zestedesavoir.com
Authorization: Bearer <Token>
Content-Type: application/json
Cache-Control: no-cache

{ "sign" : "My Little Signature" }
```

Ainsi que le stracktrace :

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Python/2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/rest_framework_extensions/etag/decorators.py", line 37, in inner
    kwargs=kwargs,
  File "/Library/Python/2.7/site-packages/rest_framework_extensions/etag/decorators.py", line 64, in process_conditional_request
    response = view_method(view_instance, request, *args, **kwargs)
  File "/Users/Odric/PycharmProjects/zds-site/zds/member/api/views.py", line 189, in put
    return self.update(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Library/Python/2.7/site-packages/rest_framework/mixins.py", line 72, in perform_update
    serializer.save()
  File "/Library/Python/2.7/site-packages/rest_framework/serializers.py", line 159, in save
    self.instance = self.update(self.instance, validated_data)
  File "/Users/Odric/PycharmProjects/zds-site/zds/member/api/serializers.py", line 99, in update
    instance.user.username = validated_data.get('user').get('username',
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by GerardPaligot** [comment]
@MrCirdo Le test avait été fait sur la bêta ou en local ?

**Comment by MrCirdo** [comment]
Il me semble que le test avait été fait en locale.

**Comment by DevHugo** [comment]
J'avais déjà réçu à le reproduire, je me souvient.

**Comment by firm1** [comment]
Bon j'ai beau essayer, impossible de reproduire ce bug.

Si personne n'y arrive, on peut peut-être fermer ?
