### ISSUE TITLE
Zeste de Savoir plus compatible avec OS X

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#2460]
Suite au merge de cette PR (https://github.com/zestedesavoir/zds-site/pull/2430) pour le support de SVG (qui, selon moi, est absurde mais bon ...), il n'est plus possible de contribuer à Zeste de Savoir avec un système OS X. Il ne connait pas l'import `cairo` :

``` console
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/debug_toolbar/models.py", line 9, in <module>
    dt_settings.patch_all()
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/debug_toolbar/settings.py", line 238, in patch_all
    patch_root_urlconf()
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/debug_toolbar/settings.py", line 226, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 507, in reverse
    app_list = resolver.app_dict[ns]
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 329, in app_dict
    self._populate()
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 267, in _populate
    for pattern in reversed(self.url_patterns):
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/Gerard/Documents/workspace-django/zds-site/zds/urls.py", line 76, in <module>
    url(r'^tutoriels/', include('zds.tutorial.urls')),
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/Gerard/Documents/workspace-django/zds-site/zds/tutorial/urls.py", line 5, in <module>
    from . import views
  File "/Users/Gerard/Documents/workspace-django/zds-site/zds/tutorial/views.py", line 23, in <module>
    import cairosvg
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/cairosvg/__init__.py", line 27, in <module>
    from . import surface
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 30, in <module>
    import cairo  # pycairo
ImportError: No module named cairo
```

Voilà, j'ai pas beaucoup de temps en ce moment, j'en avais dégagé ce soir pour un tuto et pour commencer l'API des MPs et je me retrouve bêtement bloqué parce qu'une PR n'a pas été assez testée. Franchement, ça me fait chier.

**Comment by firm1** [comment]
Pas le temps de voir pourquoi, mais [j'ai revert la PR](https://github.com/zestedesavoir/zds-site/pull/2461), du coup tu peux travailler :)

**Comment by GerardPaligot** [comment]
Merci bien @firm1.

**Comment by SpaceFox** [comment]
1. Avoir des SVG dans les tutos n'est pas absurde, c'est super pratique SVG.
2. Il me semblait qu'on avait dit que c'était absolument interdit de merger son propre code ?

**Comment by GerardPaligot** [comment]
> 1. Avoir des SVG dans les tutos n'est pas absurde, c'est super pratique SVG.

De ce que j'en vois, je suppose que nous avons intégré ce format parce que **un** tuto (à venir) en avait potentiellement besoin. Chose que nous avons finalement pas utilisé puisque nous avons pu contourner le problème.

Là avec le support du SVG, de ce que j'en vois, nous commençons à avoir des cas particuliers et ce genre de choses me gavent (sans compter le fait que l'implémentation est dégueulasse puisque nous nous battons à coup de conditions explicites).

Soit, j'ai pu travaillé hier sur l'API des MPs et pour moi, c'est ce qui m'importe. Faut voir avec @firm1 pour le merge de ses PRs.

**Comment by SpaceFox** [comment]
Ben si on arrive à servir du SVG en front, c'est super pratique : pour tous
les diagrammes, c'est plus léger et de meilleure qualité au
redimensionnement que les formats à base de pixels.

Par contre si on le convertit systématiquement avant affichage, je suis
d'accord pour dire que c'est un peu idiot.

Mais dans tous les cas, le SVG est un format qu'il serait bon de supporter,
parce que c'est pratique et que j'ai vu plusieurs fois la demande.

**Comment by firm1** [comment]
> De ce que j'en vois, je suppose que nous avons intégré ce format parce que un tuto (à venir) en avait potentiellement besoin. 

Je crois que tu te trompes. Le format a été "intégré" parce que ça fait parti d'un bug déclaré depuis le mois d'octobre qui rend la validation d'un tutoriel un peu pénible.

En tant que validateur, je suis obligé de vérifier l'extension de toutes les images (code markdown) d'un tuto pour m'assurer que l'auteur n'a pas inséré une image svg dans son tutoriel. Un auteur lambda, quand il trouve une image svg et qu'il l'insère dans ton tutoriel et que celle-ci est interprétée (comme c'est le cas aujourd'hui) il ne peut pas se douter que ça plantera à la validation. Donc c'est au validateurs de vérifier ce genre de chose aujourd'hui, et personnellement ça fait perdre du temps lors de la validation.

Je rappelle qu'ici on ne supporte que les lien svg externes. Car il n'est de toute façon pas possible d'insérer un svg dans une gallérie. En résumé, le format n'est pas réellement supporté, on s'assure juste qu'on aura pas de plantage si quelqu'un en met un.

**Comment by GerardPaligot** [comment]
Je ne prendrais pas la responsabilité de merger une fonctionnalité partiellement développée. J'informerais simplement si elle fonctionne sous OS X.

**Comment by firm1** [comment]
> Je ne prendrais pas la responsabilité de merger une fonctionnalité partiellement développée. J'informerais simplement si elle fonctionne sous OS X.

:( . A quoi sert mon pavé alors qui explique que ce n'est pas une fonctionnalité developpée, mais une correction de bug ?

**Comment by GerardPaligot** [comment]
J'ai lu ton pavé, je ne le cautionne juste pas. Qu'en est-il dans les articles ? Dans les forums ? Est-ce plus cohérent de pas faire de même dans les galeries ? Ce n'est pas cohérent.

**Comment by SpaceFox** [comment]
- On peut en effet se poser la question des articles. Ceci devrait être corrigé.
- Le problème ne se pose pas dans les forums, puisqu'ils ne sont pas exportés...
- Accepter le SVG dans les galeries serait un gros plus mais c'est encore un autre problème.

La seule incohérence ici, c'est que le problème est corrigé pour les forums mais pas pour les articles.

J'ai l'impression qu'il faut que tout le monde se calme ici...

**Comment by firm1** [comment]
> Qu'en est-il dans les articles ? Dans les forums ? Est-ce plus cohérent de pas faire de même dans les galeries ? Ce n'est pas cohérent.
- Les articles n'ont pas le bug, car ils ne sont pas exportés aujourd'hui. La PR qui fusionnera les tutoriels et article devra gérer ce cas, mais vu que le code sera fusionné, on aura pas de problème de ce coté. Autrement dit, il est déjà possible de valider un article aujourd'hui avec une image svg.
- les forums n'ont pas le problème non plus car ils ne sont pas exportés
- Le support dans les gallerie est un autre problème. Si je dois developper ça, je t'avouerai que je préfèrerait aller faire une PR sur le dépot de [Easy_thumbnails](https://github.com/SmileyChris/easy-thumbnails) pour que ça soit quasi transparent pour nous.

**Comment by SpaceFox** [comment]
Ah tiens, c'est vrai, les articles ne sont pas disponibles autrement qu'au format "archive". J'étais persuadé du contraire.

Pour le SVG et easy_thumbnails, c'est plus délicat : la notion de redimensionnement - et donc de thumbnail - n'a pas de sens sur un format vectoriel : il suffit de l'afficher au format voulu et ça suffit.

**Comment by GerardPaligot** [comment]
> J'ai l'impression qu'il faut que tout le monde se calme ici...

C'est ma faute. J'ai été prendre une grande inspiration dehors pour me calmer.  Désolé @firm1 pour ma mauvaise humeur mais ta PR m'a vraiment fait rager hier. :)

Bref ...

Je ne savais pas que c'était lié à l'export. Alors même si le SVG n'est pas géré par les galeries (bien que cela soit dommage) et que les forums sont effectivement pas sujets à l'export, je ne comprends pas trop pourquoi les articles ne le sont pas. Il y a une raison à ça ?

**Comment by firm1** [comment]
> Pour le SVG et easy_thumbnails, c'est plus délicat : la notion de redimensionnement - et donc de thumbnail - n'a pas de sens sur un format vectoriel : il suffit de l'afficher au format voulu et ça suffit.

Yop, mais j'ai l'impression qu'il faudrait passer par des pirrouettes douteuses et un peu sale si on le fait dans notre code.

> je ne comprends pas trop pourquoi les articles ne le sont pas. Il y a une raison à ça ?

La raison est que les articles ne sont pas exportés vers du pdf, epub aujourd'hui. C'est l'intéret de la ZEP12 que de le permettre en fusionnant (au sens code) les deux modules.
