### ISSUE TITLE
Plus moyen d'importer les fixtures "aides"

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2562]
À mon avis, le passage à Django 1.7 a bousillé notre script. Je cite:

```
(zdsenv)pbeaujea@chim13-cptrx04:~/Devels/zds-site$ python load_factory_data.py fixtures/advanced/aide_tuto_media.yaml
Traceback (most recent call last):                                                                                                          
  File "load_factory_data.py", line 20, in <module>                                                                                         
    m = __import__(module_part)                                       
  File "/home/pbeaujea/Devels/zds-site/zds/utils/factories.py", line 2, in <module>
    from zds.utils.models import HelpWriting
  File "/home/pbeaujea/Devels/zds-site/zds/utils/models.py", line 12, in <module>
    from zds.utils.templatetags.emarkdown import emarkdown
  File "/home/pbeaujea/Devels/zds-site/zds/utils/templatetags/emarkdown.py", line 21, in <module>
    __MD_ERROR_PARSING = _(u'Une erreur est survenue dans la génération de texte Markdown. Veuillez rapporter le bug.')
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 83, in ugettext
    return _trans.ugettext(message)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 325, in ugettext
    return do_translate(message, 'ugettext')
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 306, in do_translate
    _default = translation(settings.LANGUAGE_CODE)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 209, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 189, in _fetch
    "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
```

... Oups ^^

**Comment by Eskimon** [comment]
```
File "/home/pbeaujea/Devels/zds-site/zds/utils/templatetags/emarkdown.py", line 21, in <module>
    __MD_ERROR_PARSING = _(u'Une erreur est survenue dans la génération de texte Markdown. Veuillez rapporter le bug.')
```

Probablement ce morceau là qui gène...

**Comment by pierre-24** [comment]
Corrigé par @firm1 <3 !!!
