### ISSUE TITLE
Impossible de mettre à jours l'index des recherches

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#2648]
J'ai installé la version 4.9.1 de solr comme précisé dans la documentation. J'ai d'abord effectué la commande pour créé le schéma: 

``` python
python manage.py build_solr_schema > ../solr-4.9.1/example/solr/collection1/conf/schema.xml.
```

 La commande passe sans probléme mais quand je fais un update_index. 
J'ai l'erreur suivante :

```
Indexing 0 Articles
Indexing 6 Sujets
Indexing 7 posts
Indexing 1 Tutoriels
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 184, in handle
    return super(Command, self).handle(*items, **options)
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 189, in handle_label
    self.update_backend(label, using)
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 234, in update_backend
    do_update(backend, index, qs, start, end, total, self.verbosity)
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 89, in do_update
    backend.update(index, current_qs)
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/haystack/backends/solr_backend.py", line 54, in update
    docs.append(index.full_prepare(obj))
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/haystack/indexes.py", line 207, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/haystack/indexes.py", line 198, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/haystack/fields.py", line 159, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/haystack/fields.py", line 106, in prepare
    return current_object()
  File "/home/hugo/dev/python/zdsenvpython2/lib/python2.7/site-packages/django/db/models/fields/related.py", line 843, in __call__
    manager = getattr(self.model, kwargs.pop('manager'))
KeyError: u'manager'
```

**Comment by Eskimon** [comment]
Sur une install toute propre toute fraiche je viens de faire l'install de tout écosystème (solr inclus) et ça marche nickel. Du coup question habituelle : tes requirements sont-ils a jour ?

**Comment by DevHugo** [comment]
Ça doit venir de mon côté, je ferme alors.

**Comment by pierre-24** [comment]
Spacefox ayant rencontré la même erreur ... Ça m'inquiète.

@Eskimon : est ce que tu avais testé avec des tutos générés par les fixtures ?

@DevHugo : à un moment, il me semble que la commande te demande si tu veux supprimer l'ancien, tu as bien répondu "oui" ?

**Comment by Eskimon** [comment]
> @Eskimon : est ce que tu avais testé avec des tutos générés par les fixtures ?

Non

**Comment by pierre-24** [comment]
Aïe. J'ai peur.
