### ISSUE TITLE
[15.5.1] Erreur 500 lors de la desinscription

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#2751]
En essayant de me desinscrire, je me mange une erreur 500 et mon compte est toujours là. Testé avec un compte créé via réseau social ou par le site directement. Même résultat.

Je suis à peu près certain que ça marchait avant, donc ça ressemble a une régression.

**Comment by Eskimon** [comment]
Je viens de tester sur ma branche `dev` a jour et ca se passe bien.
Sur la branche `release` aussi ca semble bien se passer.

Du coup il va falloir absolument un log car incapable de reproduire en local.

**Comment by GerardPaligot** [comment]
Si on est incapable de se désinscrire, c'est même bloquant.

**Comment by Eskimon** [comment]
Bon, en local j'arrive a bien me desinscrire, mais sur la preprod j'y arrive pas... c'est balot... et faudra des logs :D

**Comment by Eskimon** [comment]
Est-ce qu'on pourrait avoir un truc similaire avec https://github.com/zestedesavoir/zds-site/issues/2753 ?

**Comment by Eskimon** [comment]
Stacktrace :

```
[ERROR] -- 2015-06-03 22:05:42,509 -- base : Internal Server Error: /membres/desinscrire/valider/
Traceback (most recent call last):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/opt/zdsenv/ZesteDeSavoir/zds/member/views.py", line 357, in unregister
    User.objects.filter(pk=current.pk).delete()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 556, in delete
    collector.collect(del_query)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 198, in collect
    elif sub_objs:
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 145, in __nonzero__
    self._fetch_all()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'oauth2_provider_application.skip_authorization' in 'field list'")
```

**Comment by GerardPaligot** [comment]
`OperationalError: (1054, "Unknown column 'oauth2_provider_application.skip_authorization' in 'field list'")`

Il n'y aurait pas un problème de déploiement de la branche sur le serveur ?

**Comment by Eskimon** [comment]
(J'ai oublie de le redire mais je confirme que c'est bien le meme souci que ca : https://github.com/zestedesavoir/zds-site/issues/2753 )

**Comment by pierre-24** [comment]
C'est bon :)
