### ISSUE TITLE
On ne peut plus indexer de tutoriels

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zds-site#2792]
Quand on indexe un tutoriel publié, on obtient cette erreur:

``` bash
$ python manage.py rebuild_index

WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N] y
Removing all documents from your index because you said so.
All documents removed.
Indexing 3 Articles
Indexing 4 Sujets
Indexing 5 posts
Indexing 6 Tutoriels
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/haystack/management/commands/rebuild_index.py", line 16, in handle
    call_command('update_index', **options)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 184, in handle
    return super(Command, self).handle(*items, **options)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 189, in handle_label
    self.update_backend(label, using)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 234, in update_backend
    do_update(backend, index, qs, start, end, total, self.verbosity)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 89, in do_update
    backend.update(index, current_qs)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/haystack/backends/solr_backend.py", line 54, in update
    docs.append(index.full_prepare(obj))
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/haystack/indexes.py", line 207, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/haystack/indexes.py", line 198, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/haystack/fields.py", line 159, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/haystack/fields.py", line 106, in prepare
    return current_object()
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 843, in __call__
    manager = getattr(self.model, kwargs.pop('manager'))
KeyError: u'manager'
```

J'ajoute que si le tuto est vide, ça ne change rien, donc l'erreur ne vient pas de l'indexation des parties ou chapitre.

C'est même potentiellement bloquant.

**Comment by firm1** [comment]
Ce problème n'existe pas en prod, du coup c'est une regression non ? Et je dirais même bloquante.

**Comment by GerardPaligot** [comment]
Ca dépend, est-ce que le problème survient uniquement quand ce sont des tutoriels provenant des fixtures ?

**Comment by pierre-24** [comment]
Non, j'ai testé en créant un mini-tuto vide à la main.

**Comment by firm1** [comment]
Donc on est bien sur de la regression là

**Comment by GerardPaligot** [comment]
Je sais pas. Mon cas est un peu spécial parce que je ne suis jamais parvenu à faire tourner un Solr correctement mais ça fait longtemps que j'avais un problème sur l'indexation du contenu.

**Comment by firm1** [comment]
@GerardPaligot tu peux ouvrir un thread sur ton pb d'install solr ? Normalement ça se résume à un (wget + mv + jar). C'est du java, donc ça devrait être facilement multiplateforme.

@pierre-24 si tu peux, est-ce que tu arrive à revenir sur la version de prod pour vérifier si tu reproduis le bug ?

**Comment by pierre-24** [comment]
@Spacefox [l'avait déjà reporté il y a une quinzaine de jour](https://zestedesavoir.com/forums/sujet/846/zep-12-refonte-du-principe-des-tutoriels-et-articles/?page=18#p57266). Par ailleurs, [on dirait que ça bugge sur la bêta](http://beta.zestedesavoir.com/rechercher/?q=promesse&models=tutorial.tutorial) (j'ai essayé de chercher le tuto "les promesses en javascript").

Donc "bloquant" et "régression".

D'ailleurs, [quand je cherche "ruby" en prod](https://zestedesavoir.com/rechercher/?q=Ruby&models=tutorial.tutorial), je tombe pas [sur le tuto Ruby publié il y a une semaine](https://zestedesavoir.com/tutoriels/373/une-introduction-a-ruby/). Ça m'étonne un peu, et je commence à soupçonner une régression assez importante.

**Comment by GerardPaligot** [comment]
Ca devient incontestable. Nous sommes sur de la régression bloquante.

**Comment by pierre-24** [comment]
Oui. Par contre, ça m'étonne que @SpaceFox ne l'aie pas vu, parce que si ça bugge, ça doit bugger toutes les 30 minutes.

**Comment by Eskimon** [comment]
Je vois pas en quoi c'est bloquant. Oui c'est dommage que les tutos ne soient pas indexé, mais ca n'empêche pas d’accéder au contenu, ne nous met pas dans l'illégalité etc.

**Comment by firm1** [comment]
En gros, depuis la v15.5 (peut-être même avant) on a un problème d'indexation des tutoriels en prod. et : 
- ça n'a pas été remarqué : il faudrait superviser ça
- la new-home met en avant la recherche : il faudrait que les choses soient un minimum trouvable.

**Comment by GerardPaligot** [comment]
Je complèterais les propos de @firm1 : Nous spécifions sur la page de la recherche les tutoriels. Donc si nous ne les indexons plus, nous ne proposons plus les nouveaux tutoriels et ça devient bloquant dans le cadre de cette fonctionnalité.

**Comment by pierre-24** [comment]
C'est ... "conflictuel". La doc dit ceci : 

> Le tag Bloquant : Il ne concerne que les tickets désignant un bug ou une régression qui empêchent une utilisation correcte du site (connexion impossible, forte atteinte aux performances, etc).

Si on applique la définition pure et dure, c'est pas "bloquant", c'est juste ... "ennuyeux" :p

**Comment by pierre-24** [comment]
Tient, au fait, c'est un retour de #2648 :s

**Comment by SpaceFox** [comment]
Vue l'importance de la recherche sur la nouvelle home, ce genre de gag est hélas  bloquant :(

**Comment by pierre-24** [comment]
Ping @DevHugo ?

**Comment by DevHugo** [comment]
Je suis de retour dans la soirée, je regarde ça asap.

**Comment by DevHugo** [comment]
Je suis pas sur un ordi fixe, peut tu commenter la ligne: https://github.com/DevHugo/zds-site/blob/dev/zds/tutorial/search_indexes.py#L14 et me dire si ça marche ?

**Comment by pierre-24** [comment]
Ça marche, en effet :)

**Comment by DevHugo** [comment]
Cool, un grand merci =).

Maintenant 'le pourquoi' ^^ ! Car c'est pas normal qu'on est pas eu le problème avant. 

Typiquement, pourquoi celui la, ça marche et pas l'autre https://zestedesavoir.com/rechercher/q=Les+promesses+en+JavaScript&models=tutorial.tutorial.

Ça semble pas liés au nombres de sous catégories, j'ai peur qu'on est un autre bug derrière. 

Edit: Bon j'abandonne pour la raison du problème. Si quelqu'un peut choper les logs d'un rebuild_index de la prod ou de la beta, je prends.

**Comment by DevHugo** [comment]
Je le remet ici, la PR corrige une partie du problème, celle de l'indéxaiton des catégories des tutos qui font planter l'indéxation des tutoriels. 

Sans info complémentaires des logs de l’indexation la prod, impossible de deviner le problème qui fait que certains tutoriels sont pas indexé.

**Comment by pierre-24** [comment]
Merci à vous :)
