### ISSUE TITLE
L'import de tuto est HS sous Windows avec python 2.7.6

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#287]
Windows 7 SP1, Python 2.7.6, virtualenv tout neuf.
Les tests d'import de tutos explosent avec des logs de ce genre : 

``` console
======================================================================
ERROR: test_quote_note (zds.tutorial.tests.BigTutorialTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Programmes\django\ZesteDeSavoir\zds\tutorial\tests.py", line 66, in setUp
    follow=False)
  File "C:\Users\SpaceFox\.virtualenvs\zdsenv\lib\site-packages\django\test\client.py", line 483, in post
    response = super(Client, self).post(path, data=data, content_type=content_type, **extra)
  File "C:\Users\SpaceFox\.virtualenvs\zdsenv\lib\site-packages\django\test\client.py", line 302, in post
    return self.request(**r)
  File "C:\Users\SpaceFox\.virtualenvs\zdsenv\lib\site-packages\django\test\client.py", line 444, in request
    six.reraise(*exc_info)
  File "C:\Users\SpaceFox\.virtualenvs\zdsenv\lib\site-packages\django\core\handlers\base.py", line 114, in get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Programmes\django\ZesteDeSavoir\zds\member\decorator.py", line 40, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "C:\Users\SpaceFox\.virtualenvs\zdsenv\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped
_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\SpaceFox\.virtualenvs\zdsenv\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\SpaceFox\.virtualenvs\zdsenv\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped
_view
    return view_func(request, *args, **kwargs)
  File "D:\Programmes\django\ZesteDeSavoir\zds\tutorial\views.py", line 283, in valid_tutorial
    MEP(tutorial, tutorial.sha_validation)
  File "D:\Programmes\django\ZesteDeSavoir\zds\tutorial\views.py", line 2358, in MEP
    get_url_images(md_file_contenu, tutorial.get_prod_path())
  File "D:\Programmes\django\ZesteDeSavoir\zds\tutorial\views.py", line 2269, in get_url_images
    imgs = re.findall(regex, md_text)
  File "C:\Users\SpaceFox\.virtualenvs\zdsenv\lib\re.py", line 177, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer
```

Fonctionne nickel dans une VM linux, virtualenv neuf, python 2.7.5... peut-être un problème de python (et donc à relier à l'issue #280 ?)

**Comment by cgabard** [comment]
Je ne pense pas comme ça que ce soit un prob de re. A priori ce module a bougé dans la branche 2.7 mais surtout dans les premieres revisions et on est effectivement tombé sur un bug présent dans la 2.7.3 (qui est la version utilisé par travis) mais corrigé ensuite. Là cela semble différent. 

Vu l'erreur, je serais toi, à la ligne 2269 de `zds\tutorial\views.py` je ferais un `print regex, md_text` pour être surs de ce que tu lui envoie.

J'attends que @firm1 me détail ce module mais je pense qu'il serait plus efficacement implémenté directement dans le module markdown où on dispose de l'arbre DOM en mémoire avant le rendu, c'est beaucoup plus propre et simple pour aller traiter des balises.

**Comment by firm1** [comment]
Cette issue est résolue dans la [PR suivante](https://github.com/Taluu/ZesteDeSavoir/pull/291).

@cgabard avait raison pour les valeur a vide.

> J'attends que @firm1 me détail ce module mais je pense qu'il serait plus efficacement implémenté directement dans le module markdown où on dispose de l'arbre DOM en mémoire avant le rendu, c'est beaucoup plus propre et simple pour aller traiter des balises.

Pour la petite histoire, les fichiers .tuto actuels contiennent de nombreuses urls plus ou moins pratiques. Quand je reçois un .tuto je dois identifier tous les liens des images qui ne sont pas relatives (il y'en a dans le tuto), télécharger les images, et les stocker sur le serveur. Je refais donc ensuite les chemins du style remplacer dans tout le fichier les `uploads.siteduzero.com/files/blabla.png` par `/media/galleries/tuto/blabla.png`. Je dois aussi le faire pour convetir toutes les images de type gif en jpg (sinon c'est latex qui gueulent).

En gros il y'a un enorme traitement pour rendre les images propres et cohérentes dans l'ensemble du tuto. Je ne pense donc pas que ça relève du markdown puisque la fonctionnalité n'implique que l'import des tutos et l'export (gif->jpg) des tutos.

Sur ce, je ferme l'issue. Merci pour le signalement

**Comment by SpaceFox** [comment]
"et l'export (gif->jpg) "

C'est pas adapté, la transformation devrait être gif --> png (ou alors on
garde gif)

2014-04-11 14:29 GMT+02:00 firm1 notifications@github.com:

**Comment by firm1** [comment]
Ah oui excuse moi, c'est bien une conversion de [gif vers png](https://github.com/Taluu/ZesteDeSavoir/blob/dev/zds/tutorial/views.py#L2274) qui a été implémentée

**Comment by SpaceFox** [comment]
Parfait alors :)
