### ISSUE TITLE
[V12] erreur 500 sur les commentaires d'un tutoriel

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3181]
Url incriminée:  https://zestedesavoir.com/contenus/reactions/ajouter/?pk=344

On se prend une erreur 500 qui nous demande de poster le bug ici. Voila qui est fait.

**Comment by Eskimon** [comment]
Et voici la stacktrace :

``` python
[ERROR] -- 2015-11-10 18:14:49,440 -- base : Internal Server Error: /contenus/reactions/ajouter/
Traceback (most recent call last):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/zdsenv/ZesteDeSavoir/zds/member/decorator.py", line 27, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/opt/zdsenv/ZesteDeSavoir/zds/member/decorator.py", line 66, in dispatch
    return super(LoggedWithReadWriteHability, self).dispatch(*args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/opt/zdsenv/ZesteDeSavoir/zds/member/decorator.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorialv2/mixins.py", line 444, in dispatch
    self.public_content_object = self.get_public_object()
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorialv2/mixins.py", line 352, in get_public_object
    raise MustRedirect(self.get_redirect_url(obj))
MustRedirect: /tutoriels/344/redorez-votre-blason-sur-google-bases-de-reputation-en-ligne/
```

**Comment by pierre-24** [comment]
Ah. Je pense qu'on se mange notre système de redirection dans la figure, là.

**Comment by artragis** [comment]
si on a un "must redirect" ça veut dire... que la PK n'est pas celle du véritable tuto mais de l'ancien non?

**Comment by pierre-24** [comment]
Plus que probablement.

**Comment by artragis** [comment]
Non l'id est bon, l'url est bonne c'est juste qu'on crée un must_redirect alors qu'on devrait pas. je regarde dans mes armoires si ma baguette magique est toujours là et je te fais ça dès que possible.

**Comment by pierre-24** [comment]
Sort la poupée Vaudou, aussi.

**Comment by artragis** [comment]
:p

**Comment by SpaceFox** [comment]
Corrigé et mergé --> fermé
