### ISSUE TITLE
Les tests ne passent plus sur OS X

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3187]
Sur la dernière version de dev (commit 2fcbf7760476be6534e63a7121ad4326ce253425), les tests ne passent plus sur le système OS X. Voici l'output :

``` console
======================================================================
ERROR: test_public_tutorial (zds.tutorial.tests.tests.BigTutorialTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/tutorial/tests/tests.py", line 228, in test_public_tutorial
    follow=False)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/test/client.py", line 482, in post
    secure=secure, **extra)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/test/client.py", line 296, in post
    secure=secure, **extra)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/test/client.py", line 358, in generic
    return self.request(**r)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/test/client.py", line 440, in request
    six.reraise(*exc_info)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/member/decorator.py", line 27, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/tutorial/views.py", line 363, in valid_tutorial
    mep(tutorial, tutorial.sha_validation)
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/tutorial/views.py", line 3318, in mep
    get_url_images(md_file_contenu.encode('utf-8'), prod_path)
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/tutorial/views.py", line 3158, in get_url_images
    resize_svg(down_path)
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/tutorial/views.py", line 3206, in resize_svg
    tree = etree.parse(source)
  File "lxml.etree.pyx", line 3310, in lxml.etree.parse (src/lxml/lxml.etree.c:72517)
  File "parser.pxi", line 1791, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:105979)
  File "parser.pxi", line 1817, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:106278)
  File "parser.pxi", line 1721, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:105277)
  File "parser.pxi", line 1122, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:100227)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94853)
XMLSyntaxError: Document is empty, line 1, column 1

======================================================================
ERROR: test_quote_note (zds.tutorial.tests.tests.BigTutorialTests)
check quote of note.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/tutorial/tests/tests.py", line 72, in setUp
    self.bigtuto = BigTutorialFactory(light=True)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/factory/base.py", line 82, in __call__
    return cls.create(**kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/factory/base.py", line 585, in create
    return cls._generate(True, attrs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/factory/base.py", line 510, in _generate
    obj = cls._prepare(create, **attrs)
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/tutorial/factories.py", line 75, in _prepare
    repo.index.add(['manifest.json', tuto.introduction, tuto.conclusion])
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/git/index/base.py", line 726, in add
    entries_added.extend(self._entries_for_paths(paths, path_rewriter, fprogress, entries))
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/git/util.py", line 54, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/git/index/util.py", line 81, in set_git_working_dir
    cur_wd = os.getcwd()
OSError: [Errno 2] No such file or directory

# Plein d'autres comme ça avec OSError: [Errno 2] No such file or directory

======================================================================
ERROR: test_load_fixtures (zds.utils.management.tests.CommandsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/utils/management/tests.py", line 22, in test_load_fixtures
    call_command('load_fixtures', *args, **opts)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/utils/management/commands/load_fixtures.py", line 893, in handle
    load_articles(self, size, fake)
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/utils/management/commands/load_fixtures.py", line 610, in load_articles
    description=fake.sentence(nb_words=15, variable_nb_words=True))
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/factory/base.py", line 82, in __call__
    return cls.create(**kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/factory/base.py", line 585, in create
    return cls._generate(True, attrs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/factory/base.py", line 510, in _generate
    obj = cls._prepare(create, **attrs)
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/article/factories.py", line 70, in _prepare
    repo.index.add(['manifest.json', article.text])
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/git/index/base.py", line 726, in add
    entries_added.extend(self._entries_for_paths(paths, path_rewriter, fprogress, entries))
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/git/util.py", line 54, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/git/index/util.py", line 81, in set_git_working_dir
    cur_wd = os.getcwd()
OSError: [Errno 2] No such file or directory

======================================================================
FAIL: test_success_new_image_write_permission (zds.gallery.tests.tests_views.NewImageViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/gallery/tests/tests_views.py", line 636, in test_success_new_image_write_permission
    self.assertEqual(2, len(os.listdir(self.gallery.get_gallery_path())))  # New image and thumbnail
AssertionError: 2 != 3

======================================================================
FAIL: test_load_factory_data (zds.utils.management.tests.CommandsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/utils/management/tests.py", line 51, in test_load_factory_data
    self.assertTrue(HelpWriting.objects.count() > 0)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 802 tests in 253.520s
```

**Comment by artragis** [comment]
> ```
> ======================================================================
> FAIL: test_success_new_image_write_permission (zds.gallery.tests.tests_views.NewImageViewTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/Users/gerard/Documents/workspace-django/zds-site/zds/gallery/tests/tests_views.py", line 636, in test_success_new_image_write_permission
>     self.assertEqual(2, len(os.listdir(self.gallery.get_gallery_path())))  # New image and thumbnail
> AssertionError: 2 != 3
> ```

ne passe plus non plus sous windows avec la même erreur.

**Comment by pierre-24** [comment]
Et sous linux mint non plus, en fait.

**Comment by SpaceFox** [comment]
Bizarre… je testerai sous Ubuntu Gnome cet après-midi.

**Comment by GerardPaligot** [comment]
Linux devrait fonctionner puisque Travis passe sur les tests, non ?

**Comment by gustavi** [comment]
@pierre-24 on peut avoir un `pip freeze` et un `uname -a` ?

**Comment by pierre-24** [comment]
Tout de suite : 
- Je suis bien sur dev:

```
(zdsenv)pbeaujea@chim13-cptrx04 ~/Devels/zds-site $ git status
HEAD detached at upstream/dev
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        conf.cnf
        doc/requirements-rtd.txt
        doc/tmp.log
        fixtures/tuto/article_v1.zip
        fixtures/tuto/article_v1/manifest2.json
        fixtures/tuto/balise_audio.zip
        fixtures/tuto/big_tuto_v1.zip
        zdsenv/

nothing added to commit but untracked files present (use "git add" to track)
```
- Le test seul réussi : 

```
(zdsenv)pbeaujea@chim13-cptrx04 ~/Devels/zds-site $ python manage.py test zds.gallery.tests.tests_views.NewImageViewTest.test_success_new_image_write_permission
Creating test database for alias 'default'...
.
----------------------------------------------------------------------
Ran 1 test in 0.476s

OK
Destroying test database for alias 'default'...
```
- Le test parmi plusieurs tests échoue:

```
(zdsenv)pbeaujea@chim13-cptrx04 ~/Devels/zds-site $ python manage.py test zds.gallery.tests.tests_views.NewImageViewTest
Creating test database for alias 'default'...
......F
======================================================================
FAIL: test_success_new_image_write_permission (zds.gallery.tests.tests_views.NewImageViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pbeaujea/Devels/zds-site/zds/gallery/tests/tests_views.py", line 636, in test_success_new_image_write_permission
    self.assertEqual(2, len(os.listdir(self.gallery.get_gallery_path())))  # New image and thumbnail
AssertionError: 2 != 3

----------------------------------------------------------------------
Ran 7 tests in 1.550s

FAILED (failures=1)
Destroying test database for alias 'default'...
```
- Le noyau:

```
(zdsenv)pbeaujea@chim13-cptrx04 ~/Devels/zds-site $ uname -r
3.13.0-37-generic
```
- Le `pip freeze` :

```
(zdsenv)pbeaujea@chim13-cptrx04 ~/Devels/zds-site $ pip freeze
/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.0.3, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
autopep8==1.1.1
beautifulsoup4==4.3.2
cairocffi==0.7
CairoSVG==1.0.13
cffi==1.1.2
coverage==3.7.1
defusedxml==0.4.1
Django==1.7.7
django-braces==1.8.0
django-cors-headers==1.0.0
django-crispy-forms==1.4.0
django-debug-toolbar==1.2.2
django-filter==0.9.2
django-haystack==2.3.1
django-model-utils==2.2
django-munin==0.1.5
django-oauth-toolkit==0.7.2
django-recaptcha==1.0.4
django-rest-swagger==0.2.9
django-uuslug==1.0.3
djangorestframework==3.1.1
djangorestframework-xml==1.0.1
docutils==0.12
drf-extensions==0.2.7
easy-thumbnails==2.2
factory-boy==2.4.1
fake-factory==0.5.0
flake8==2.3.0
gitdb==0.6.4
GitPython==0.3.6
Jinja2==2.7.3
lxml==3.4.2
Markdown==2.6.post7
MarkupSafe==0.23
mccabe==0.3.1
MySQL-python==1.2.5
oauthlib==0.7.2
pep8==1.6.2
Pillow==2.7.0
pycparser==2.14
pyflakes==0.9.2
pygeoip==0.3.2
Pygments==2.0.2
PyJWT==0.4.1
pysolr==3.3.0
python-memcached==1.53
python-openid==2.2.5
python-slugify==1.1.2
python-social-auth==0.2.2
PyYAML==3.11
requests==2.7.0
requests-oauthlib==0.5.0
six==1.9.0
smmap==0.9.0
Sphinx==1.2.3
sphinx-rtd-theme==0.1.6
sqlparse==0.1.15
Unidecode==0.4.18
wheel==0.24.0
```

**Comment by pierre-24** [comment]
Ceci étant dit, je soupconne la gallerie de contenir ... Un `.silex` ?!?

(ajoutez à cela que la batterie de test détruit joyeusement toutes mes galeries existantes, il faudra [rajouter cette ligne](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/tests/tests_views.py#L48) au dessus de tout les tests)

**Comment by pierre-24** [comment]
Je confirme, y'a un `.silex` que je sais pas ce qu'il fout là : 

![screenshot from 2015-11-23 22 35 23](https://cloud.githubusercontent.com/assets/7889675/11350594/90518894-9232-11e5-9897-8643b4a2ff72.png)

**Comment by AmarOk1412** [comment]
fixé ?

**Comment by motet-a** [comment]
Bon je ferme, chez moi ça marche et toutes les sources des tutoriels ont dû complètement changer depuis et personne n’a l’air de se plaindre.
