### ISSUE TITLE
le front ne build pas sur windows

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zds-site#3198]
Mon installation: 
dernière version de node (sur leur site)
- npm install
- npm install gulp bower
- npm install

puis : 

``` bash
PS D:\zds-site> npm run gulp -- build

> zds-site@0.2.0 gulp D:\zds-site
> gulp "build"

[22:31:16] Using gulpfile D:\zds-site\Gulpfile.js
[22:31:16] Starting 'sprite'...
[22:31:19] Starting 'vendors-js'...
[22:31:19] Starting 'vendors-css'...
[22:31:19] Starting 'scripts'...
[22:31:21] 'scripts' errored after 1.22 s
[22:31:21] Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\zds-site\node_modules\gulp-size\node_modules\gulp-util\node_modules\multipipe\node_modules\duplexer2\node_modules\readable-stream\lib\_stream_readable.js:47:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\zds-site\node_modules\gulp-size\node_modules\gulp-util\node_modules\multipipe\node_modules\duplexer2\node_modules\readable-stream\readable.js:1:90)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
[22:31:21] Finished 'vendors-css' after 1.28 s
[22:31:21] Finished 'vendors-js' after 1.32 s
[22:31:24] gulp-imagemin: Minified 2 images (saved 71.85 kB - 45.9%)
[22:31:24] Finished 'sprite' after 8.15 s

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp" "--" "build"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! zds-site@0.2.0 gulp: `gulp "build"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zds-site@0.2.0 gulp script 'gulp "build"'.
npm ERR! This is most likely a problem with the zds-site package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp "build"
npm ERR! You can get their info via:
npm ERR!     npm owner ls zds-site
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\zds-site\npm-debug.log
PS D:\zds-site> cat .\npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'gulp',
1 verbose cli   '--',
1 verbose cli   'build' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
5 info pregulp zds-site@0.2.0
6 info gulp zds-site@0.2.0
7 verbose unsafe-perm in lifecycle true
8 info zds-site@0.2.0 Failed to exec gulp script
9 verbose stack Error: zds-site@0.2.0 gulp: `gulp "build"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid zds-site@0.2.0
11 verbose cwd D:\zds-site
12 error Windows_NT 10.0.10240
13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp" "--" "build"
14 error node v4.2.2
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error zds-site@0.2.0 gulp: `gulp "build"`
17 error Exit status 1
18 error Failed at the zds-site@0.2.0 gulp script 'gulp "build"'.
18 error This is most likely a problem with the zds-site package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp "build"
18 error You can get their info via:
18 error     npm owner ls zds-site
```

**Comment by Situphen** [comment]
1. On ne supporte pas Windows
2. Il se peut que cette version de Node ne soit pas supportée

ping @sandhose ?

**Comment by sandhose** [comment]
La 4.x de node à priori fonctionne

Par contre contre ta version de npm est pas tout à fait à jour: `npm install -g npm` pour la mettre à jour

`npm install gulp bower` n'était pas je pense une bonne idée (c'est plus dans la doc d'ailleurs), puisque ça a dû mettre la dernière version de gulp sans mettre à jour le reste

Le mieux donc est de supprimer le dossier `node_modules/`, et _juste_ lancer un `npm install`.

**Comment by artragis** [comment]
avec bien du mal, j'y suis arrivé (les anciennes dépendances avait créé des fichiers top longs). Je ferme car du coup on supporte officiellement windows.
