### ISSUE TITLE
Erreur SQL lors du déploiement en PROD de la v15.1

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3304]
À priori, c'est pas en bêta, ce qui me fait encore plus flipper…

```
Operations to perform:
  Synchronize unmigrated apps: corsheaders, raven_contrib_django, captcha, munin, debug_toolbar, sitemaps, rest_framework_swagger, rest_framework, haystack, crispy_forms
  Apply all migrations: oauth2_provider, search, tutorialv2, forum, sessions, admin, utils, featured, auth, gallery, member, default, contenttypes, mp, sites, article, easy_thumbnails, tutorial
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying oauth2_provider.0002_08_updates...Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 37, in database_forwards
    field,
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/mysql/schema.py", line 42, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 388, in add_field
    self.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1060, "Duplicate column name 'skip_authorization'")
Sentry is attempting to send 2 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

À noter que ça n'empêche pas le déploiement en prod et l'application de tourner. C'est « juste » qu'on a une colonne en trop dans notre BDD de prod, et donc des migrations qui ne correspondent pas à la base.

J'aimerais savoir par quel miracle c'est possible…

**Comment by SpaceFox** [comment]
Sentry pour ceux qui y ont accès : https://github.com/zestedesavoir/zds-site/issues/3303

**Comment by gustavi** [comment]
Potentiellement on doit pouvoir rajouter un truc comme ça à Travis pour check : 

``` shell
check_migrations()
{
    if [[ $(python manage.py makemigrations) ]]; then
        echo "You forgot to create migrations. Please run python manage.py makemigrations !" >&2
        exit 1
    fi
}
```

**Comment by SpaceFox** [comment]
Après une étude et une discussion dont les détails ne sont pas très passionnants, il _semblerait_ que ce soit un problème avec les migrations de oauth2_provider, et on se retrouve avec une colonne en trop dans la BDD. Colonne qui ne contient que la valeur par défaut. De plus, on a aucun problème à lancer les migrations sur une base propre - signe que les migrations sont cohérentes.

Voici ce qu'on va faire :
1. Si quelqu'un a une idée plus intelligente que ce qui est proposé, il a jusqu'à la MEP de la v16 pour la proposer
2. **Avant** le lancement du déploiement, vérifier si la colonne `oauth2_provider_application.skip_authorization` existe. Si oui, la supprimer. (On trouve des problèmes similaires sur le net, les solutions proposées sont celle-ci, ou des versions compliquées de celle-ci)
3. Lancer le déploiement.
4. Si le problème ou un problème se reproduit, cf https://docs.djangoproject.com/fr/1.7/topics/migrations/#upgrading-from-south

@gustavi j'ai oublié un truc important ?

**Comment by gustavi** [comment]
Non c'est bon. On rajoutera que c'est toujours la même lib qui est chiante.

**Comment by GerardPaligot** [comment]
@SpaceFox Pour résoudre l'issue, tu veux une PR qui décrit quelque part la procédure à appliquer si on rencontre ce problème ?

**Comment by SpaceFox** [comment]
Je peux la faire, c'est juste qu'il faut que je trouve la demi-heure nécessaire.
