### ISSUE TITLE
Les fixtures "normales" ne s'installent plus

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/zds-site#3332]
Depuis le merge de [l'indexation delta des forums](https://github.com/zestedesavoir/zds-site/pull/3287), les fixtures ne s'installent plus. 

``` console
$ python manage.py loaddata fixtures/*.yaml 
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 61, in handle
    self.loaddata(fixture_labels)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 91, in loaddata
    self.load_label(fixture_label)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 148, in load_label
    obj.save(using=self.using)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/serializers/base.py", line 173, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: Problem installing fixture '/Users/gerard/Documents/workspace-django/zds-site/fixtures/topics.yaml': Could not load forum.Topic(pk=1): NOT NULL constraint failed: forum_topic.update_index_date
```

**Comment by pierre-24** [comment]
Ok :)
