### ISSUE TITLE
Problème d'intégrité des fixtures

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#3417]
Les logs parlent d'eux même : 

```
python manage.py loaddata fixtures/advanced/*
/home/augustin/.virtualenvs/zds/lib/python2.7/site-packages/south/modelsinspector.py:20: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/augustin/.virtualenvs/zds/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/augustin/.virtualenvs/zds/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/augustin/.virtualenvs/zds/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/augustin/.virtualenvs/zds/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/augustin/.virtualenvs/zds/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/home/augustin/.virtualenvs/zds/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 100, in loaddata
    self.load_label(fixture_label)
  File "/home/augustin/.virtualenvs/zds/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 151, in load_label
    for obj in objects:
  File "/home/augustin/.virtualenvs/zds/lib/python2.7/site-packages/django/core/serializers/pyyaml.py", line 79, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/home/augustin/.virtualenvs/zds/lib/python2.7/site-packages/django/core/serializers/pyyaml.py", line 73, in Deserializer
    for obj in PythonDeserializer(yaml.load(stream, Loader=SafeLoader), **options):
  File "/home/augustin/.virtualenvs/zds/lib/python2.7/site-packages/django/core/serializers/python.py", line 96, in Deserializer
    Model = _get_model(d["model"])
django.core.serializers.base.DeserializationError: Problem installing fixture '/home/augustin/.virtualenvs/zds/zds-site/fixtures/advanced/aide_tuto_media.yaml': u'model'
```

Notes : DB propre, version de dev, `python manage.py migrate && python manage.py loaddata fixtures/*.yaml && python manage.py loaddata fixtures/advanced/*`

**Comment by artragis** [comment]
`python manage.py loaddata fixtures/advanced/*` nope. théoriquement tu aurais dû faire `python manage.py load_factory_data fixtures/advanced/*` mais pour une raison qui m'échappe le \* ne fonctionne plus. Donc `python manage.py load_factory_data fixtures/advanced/aide_tuto.yaml` il me semble.

Le ticket est à fermer, la documentation explique déjà ce qui concerne le dossier advanced des fixtures.

**Comment by gustavi** [comment]
C'est `*.yaml` c'est pour ça. Je ferme ici donc.
