### ISSUE TITLE
ZEP-25 : la migration ne passe pas

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/zds-site#3482]
Sortie standard :

``` console
(zdsenv)zds@vps41247:/opt/zdsenv/ZesteDeSavoir$ python manage.py migrate_to_zep25
[ZEP-25] : Tag "c plus plus" added
[ZEP-25] : Tag "word" added
[ZEP-25] : Tag "c sharp" added
[ZEP-25] : Tag "julia" added
[ZEP-25] : Tag "litterature" added
[ZEP-25] : Tag "1eravril" added
[ZEP-25] : Tag "tcp_ip" added
[ZEP-25] : Tag "html css" added
[ZEP-25] : Tag "node js" added
[ZEP-25] : Tag "angular js" added
[ZEP-25] : Tag "oxygen" added
[ZEP-25] : Tag "actionscript" added
[ZEP-25] : Tag "ror" added
[ZEP-25] : Tag "lisp" added
[ZEP-25] : Tag "disques durs" added
[ZEP-25] : Tag "memoires" added
[ZEP-25] : 16 new tag(s)
[ZEP-25] : Old category "Windows" deleted
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorialv2/management/commands/migrate_to_zep25.py", line 272, in handle
    update_categories()
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorialv2/management/commands/migrate_to_zep25.py", line 49, in update_categories
    cat.delete()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 896, in delete
    collector.delete()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 309, in delete
    query.delete_batch(pk_list, self.using)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 41, in delete_batch
    self.do_query(self.get_meta().db_table, self.where, using=using)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 26, in do_query
    self.get_compiler(using).execute_sql(NO_RESULTS)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`zdsdb`.`article_article_subcategory`, CONSTRAINT `subcategory_id_refs_id_173b0194` FOREIGN KEY (`subcategory_id`) REFERENCES `utils_subcategory` (`id`))')
Sentry is attempting to send 2 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

Ce qui a été fait :
1. Migration standard
2. `python manage.py migrate_subscriptions` (OK)

**Comment by gustavi** [comment]
`python manage.py migrate_subscriptions` ça ne concerne pas la ZEP-25.

Pour le reste je vais regarder demain.

**Comment by SpaceFox** [comment]
Je sais, c'est au cas où ça provoquait un conflit.

**Comment by SpaceFox** [comment]
Test : @sandhose  @tsirenuitrseirtceaiasuerta (vous pouvez ignorer ce message)

**Comment by gustavi** [comment]
@SpaceFox on a trouvé (il semblerait) avec @artragis !

```
django.db.utils.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`zdsdb`.`article_article_subcategory`, CONSTRAINT `subcategory_id_refs_id_173b0194` FOREIGN KEY (`subcategory_id`) REFERENCES `utils_subcategory` (`id`))')
```

**article_article_subcategory** : la table `article` semble être en cause.

**Comment by artragis** [comment]
Il suffit d'ajouter ces deux consignes au upgrade.md:

se connecter au serveur mysql et exécuter :

``` sql
DROP TABLE article_article_subcategory;
DROP TABLE tutorial_tutorial_subcategory;
```

**Comment by SpaceFox** [comment]
Tu me fais une petite PR ?

**Comment by gustavi** [comment]
@SpaceFox je débug sur la beta pour que tout soit parfait histoire de n'en avoir qu'une seule à faire et je te fais ça :)

Note : faudra refaire le BDD de la beta car j'ai "cassé" des trucs pendants mes tests (on n'a plus une version comme la prod)
