### ISSUE TITLE
[v18] Impossible de suivre un sujet

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zds-site#3499]
OS Windows
Navigateur Firefox
Version 18

Procédure :  
- Aller sur n'importe quel topic ( [celui-ci par exemple](https://beta.zestedesavoir.com/forums/sujet/4795/export-html-les-images-ne-passent-pas/) )
- Cliquer sur "suivre ce sujet"
- La _toggle_ ne change pas de couleur, et visiblement le sujet n'a pas été suivis derrière.

**Comment by GerardPaligot** [comment]
Non, là il y a un problème. Je suis certain à 300% que ça fonctionnait correctement en local. Je vais revérifier en local dès que possible.

**Comment by SpaceFox** [comment]
Cause : une erreur 500 sur l'AJAX quand on tente de suivre un topic.

L'erreur en question :

```
[ERROR] -- 2016-04-04 21:05:36,103 -- base : Internal Server Error: /forums/sujet/editer/
Traceback (most recent call last):
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/zdsenv/ZesteDeSavoir/zds/member/decorator.py", line 27, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/opt/zdsenv/ZesteDeSavoir/zds/forum/views.py", line 248, in dispatch
    return super(TopicEdit, self).dispatch(request, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/zdsenv/ZesteDeSavoir/zds/forum/views.py", line 303, in post
    return HttpResponse(json.dumps(response), content_type='application/json')
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <TopicAnswerSubscription: <Abonnement du membre "SpaceFox" aux réponses au sujet #620>> is not JSON serializable
```
