### ISSUE TITLE
Problème de migration de la ZEP-25

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#3534]
Logs: (cc @gustavi )

```
[ZEP-25] : Tag "c plus plus" added
[ZEP-25] : Tag "word" added
[ZEP-25] : Tag "c sharp" added
[ZEP-25] : Tag "julia" added
[ZEP-25] : Tag "litterature" added
[ZEP-25] : Tag "1eravril" added
[ZEP-25] : Tag "tcp_ip" added
[ZEP-25] : Tag "html css" added
[ZEP-25] : Tag "node js" added
[ZEP-25] : Tag "angular js" added
[ZEP-25] : Tag "oxygen" added
[ZEP-25] : Tag "actionscript" added
[ZEP-25] : Tag "ror" added
[ZEP-25] : Tag "lisp" added
[ZEP-25] : Tag "disques durs" added
[ZEP-25] : Tag "memoires" added
[ZEP-25] : 16 new tag(s)
[ZEP-25] : Try to delete relation "Java" <--> "Langages de programmation"
[ZEP-25] : Relation "Java" <--> "Langages de programmation" deleted
[ZEP-25] : Try to delete relation "C++" <--> "Langages de programmation"
[ZEP-25] : Relation "C++" <--> "Langages de programmation" deleted
[ZEP-25] : Try to delete relation "C#" <--> "Langages de programmation"
[ZEP-25] : Relation "C#" <--> "Langages de programmation" deleted
[ZEP-25] : Try to delete relation "Ada" <--> "Langages de programmation"
[ZEP-25] : Relation "Ada" <--> "Langages de programmation" deleted
[ZEP-25] : Try to delete relation ".NET" <--> "Langages de programmation"
[ZEP-25] : Relation ".NET" <--> "Langages de programmation" deleted
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorialv2/management/commands/migrate_to_zep25.py", line 284, in handle
    update_categories()
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorialv2/management/commands/migrate_to_zep25.py", line 50, in update_categories
    print(u'[ZEP-25] : Try to delete relation "{}" <--> "{}"'.format(cat.subcategory, cat.category))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 61: ordinal not in range(128)
```

**Comment by sandhose** [comment]
En enlevant tous les `u` devant les strings des prints du script (c'est du monkey-patching dégueu, je sais.), j'ai réussi à passer outre cette erreur. Voici (une partie) des logs:

https://gist.github.com/sandhose/74378c5d8efe375454e452dd49d022c9
