### ISSUE TITLE
[Forum] Impossible de créer un sujet avec un titre long

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/zds-site#358]
Le formulaire de création de sujet limite le titre à 80 caractères, or à une telle longueur on a le droit à une erreur 500.

**Comment by SpaceFox** [comment]
Je prends.

**Comment by SpaceFox** [comment]
Haha, connard de Sqlite qui n'a pas de contraintes de longueur de champs...

**Comment by Alex-D** [comment]
Le site n'est pas sur PostgreSQL ? Et la contrainte doit être gérée dans le code pour afficher un message de toute façon.

**Comment by SpaceFox** [comment]
Sisi, le site est sous PostgreSQL. Mais pas les environnements de dev, donc
ça on avait aucune chance de le voir...

**Comment by SpaceFox** [comment]
Logique : le formulaire est limité à 80 caractères, mais la base à 60...

**Comment by Alex-D** [comment]
Mets 80, 60 c'est vraiment trop court

**Comment by SpaceFox** [comment]
Ha ouais, en fait y'a des _dizaines_ d'incohérences de ce type... j'ai trouvé une combine pour aligner les champs automatiquement, je l'applique partout :)

**Comment by Alex-D** [comment]
Fixé et mergé

**Comment by Alex-D** [comment]
Je viens de retomber sur le bug pour le titre d'un topic dans le forum... donc je réouvre :/

**Comment by SpaceFox** [comment]
C'est étrange… c'est comme si la base n'avait pas été mise à jour.

**Comment by firm1** [comment]
lol, j'ai fais la MAJ sans migrate sur la BD. Désolé, je rectifie le tir

**Comment by firm1** [comment]
Bon la migration de l'app member echoue (alors que les autres apps sont passées). Le log est ci-dessous : 

```
Running migrations for utils:
- Nothing to migrate.
 - Loading initial data for utils.
Installed 0 object(s) from 0 fixture(s)
(zdsenv)root@vps41247:/opt/zdsenv/ZesteDeSavoir# python manage.py migrate forum
Running migrations for forum:
 - Migrating forwards to 0002_auto__chg_field_topic_subtitle__chg_field_topic_title.
 > forum:0002_auto__chg_field_topic_subtitle__chg_field_topic_title
 - Loading initial data for forum.
Installed 0 object(s) from 0 fixture(s)
(zdsenv)root@vps41247:/opt/zdsenv/ZesteDeSavoir# python manage.py migrate member
Running migrations for member:
 - Migrating forwards to 0002_auto__chg_field_profile_sign.
 > member:0002_auto__chg_field_profile_sign
FATAL ERROR - The following SQL query failed: ALTER TABLE "member_profile" ALTER COLUMN "sign" TYPE varchar(250), ALTER COLUMN "sign" SET NOT NULL, ALTER COLUMN "sign" DROP DEFAULT;
The error was: value too long for type character varying(250)

Error in migration: member:0002_auto__chg_field_profile_sign
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 254, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 329, in migrate_many
    result = self.migrate(migration, database)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/opt/zdsenv/ZesteDeSavoir/zds/member/migrations/0002_auto__chg_field_profile_sign.py", line 13, in forwards
    db.alter_column(u'member_profile', 'sign', self.gf('django.db.models.fields.CharField')(max_length=250))
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/db/generic.py", line 535, in alter_column
    flatten(values),
  File "/opt/zdsenv/local/lib/python2.7/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(250)

```

**Comment by SpaceFox** [comment]
Visiblement Postgresql a une restriction à la con sur la taille d'un
"varying"... putain, je rêve d'un monde où tous les SDGB respectent la
norme SQL.

2014-05-03 0:06 GMT+02:00 firm1 notifications@github.com:

**Comment by firm1** [comment]
Si tu parviens à corriger ça, il faudra virer le fichier de migration 0002 de member avant de pousser une PR

**Comment by SpaceFox** [comment]
En fait, je peux même pas _tester_ ce genre de connerie en local... je
commence à me demander si on aurait pas mieux fait de mettre du MySQL.

**Comment by firm1** [comment]
> on aurait pas mieux fait de mettre du MySQL.

Sur la prod ? Non, les perfs nous auraient tués

**Comment by SpaceFox** [comment]
> Sur la prod ? Non, les perfs nous auraient tués

LOL.

Sérieusement, si tu voyais ce qu'on fait tourner au taff avec du MySQL...
les versions modernes (5.0 et surtout 5.5+) gèrent parfaitement des sites
bien plus gros que ça (exemples : http://www.fnacspectacles.com ou
http://www.editionsatlas.fr)
Je vais même m'amuser à installer un PostgreSQL sur ma VM juste pour tester
tiens... mais je préviens tout de suite, j'ai jamais utilisé ce truc.

**Comment by firm1** [comment]
> Sérieusement, si tu voyais ce qu'on fait tourner au taff avec du MySQL...
> les versions modernes (5.0 et surtout 5.5+) gèrent parfaitement des sites
> bien plus gros que ça

Bah, j'imagines surtout que les mecs font pas tourner ça sur un VPS mini-cores avec même pas 3Go de RAM.

**Comment by Alex-D** [comment]
HS : PostgreSQL est bien plus complet et puissant que MySQL/MariaDB. Je ne peux qu'appuyer ce choix.
Il ne me semble pas déconnant d'avoir un SGBDR qui tourne sur un serveur de cette taille. Il faut par contre optimiser le nombre de requêtes, clairement mais ça c'est l'objet de l'autre issue.

**Comment by geoffreyc** [comment]
Mouai, c'est pas aussi black and white ! J'ai vue beaucoup de cas ou mysql
etait beaucoup plus adapté que postgresql.

2014-05-02 23:20 GMT+01:00 DEMODE Alexandre notifications@github.com:

**Comment by SpaceFox** [comment]
Complètement : on est plus en 2006. D'autant qu'on utilise aucune
fonctionnalité "avancée" (trigger, procédures stockées, contraintes
tordues, vues matérialisées, etc.)
Sur ce, je retourne à mon test.

**Comment by firm1** [comment]
Fixé.
