### ISSUE TITLE
Problèmes de migrations (ZEP25 + suppression des anciennes tables)

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#3584]
Pendant la commande `python manage.py migrate_to_zep25`:

```
[ZEP-25] : New category "Physique" for content "La science au Moyen-e et sous l'Ancien Régime : l'exemple des comètes"
[ZEP-25] : New category "Physique" for content "La limite de Landauer"
[ZEP-25] : New category "Physique" for content "La physique au temps de Newton"
[ZEP-25] : New category "Physique" for content "Pourquoi devons-nous changer de téléviseur en 2016?"
[ZEP-25] : New category "Physique" for content "Comment marchent les disjoncteurs?"
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorialv2/management/commands/migrate_to_zep25.py", line 284, in handle
    self.migrate_zds()
  File "/opt/zdsenv/ZesteDeSavoir/zds/tutorialv2/management/commands/migrate_to_zep25.py", line 231, in migrate_zds
    subcategory = SubCategory.objects.get(title=subcat)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/zdsenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
zds.utils.models.DoesNotExist: SubCategory matching query does not exist.
```

---

Lors de la suppression des anciennes tables: (voir https://github.com/zestedesavoir/zds-site/blob/release-v18/update.md#supprimer-toute-trace-des-tables-pré-zep-12 )

```
mysql> UPDATE tutorial_tutorial SET last_note_pk=NULL;
ERROR 1054 (42S22): Unknown column 'last_note_pk' in 'field list'
mysql> UPDATE article_article SET last_reaction=NULL;
ERROR 1054 (42S22): Unknown column 'last_reaction' in 'field list'
mysql> DROP TABLE tutorial_tutorial_subcategory;
ERROR 1051 (42S02): Unknown table 'tutorial_tutorial_subcategory'
mysql> DROP TABLE tutorial_tutorial_authors;
Query OK, 0 rows affected (0.08 sec)

mysql> DROP TABLE tutorial_note;
ERROR 1217 (23000): Cannot delete or update a parent row: a foreign key constraint fails
mysql> DROP TABLE tutorial_tutorialread;
Query OK, 0 rows affected (0.02 sec)
mysql> DROP TABLE tutorial_tutorial;
ERROR 1217 (23000): Cannot delete or update a parent row: a foreign key constraint fails
mysql> DROP TABLE article_article_subcategory;
ERROR 1051 (42S02): Unknown table 'article_article_subcategory'
mysql> DROP TABLE article_article_authors;
Query OK, 0 rows affected (0.06 sec)

mysql> DROP TABLE article_reaction;
ERROR 1217 (23000): Cannot delete or update a parent row: a foreign key constraint fails
mysql> DROP TABLE article_articleread;
Query OK, 0 rows affected (0.05 sec)

mysql> DROP TABLE article_article;
ERROR 1217 (23000): Cannot delete or update a parent row: a foreign key constraint fails
```

**Comment by sandhose** [comment]
cc @gustavi @SpaceFox

**Comment by gustavi** [comment]
WTF. C'est ici https://github.com/zestedesavoir/zds-site/blob/release-v18/zds/tutorialv2/management/commands/migrate_to_zep25.py#L231 donc on a soit un titre qui n'est pas bon soit c'est encore UTF-8. Je regarde mais je ne comprends pas comment c'est possible.

http://stackoverflow.com/a/17828127 ?

EDIT : je regarde ça d'ici quelques heures, impossible de me connecter en SSH où je suis.

**Comment by GerardPaligot** [comment]
Personne n'a envie d'annuler la v18 mais c'est ce qui pourrait bien arriver si on ne débloque pas la situation rapidement ...

@sandhose Tu sais sur quel tutoriel le script plante pour filer les données à @gustavi ?
@artragis Tu serais nous dire pourquoi le DROP des tables n'a pas fonctionné ?

**Comment by DevHugo** [comment]
Visiblement il a pas trouvé les deux premiers champs, ni la table et les autres sont les conséquences des premiers echec.

@sandhose y'a quoi dans la table, tutorial_tutorial et article_article comme champs ?

**Comment by artragis** [comment]
J'ai créé ces regex à partir des fichiers tels qu'ils étaient dans
l'historique git, il se peut qu'il y ait des problèmes dans le nommage,
mais comme je n'ai pas accès à la béta, je ne saurai vous dire.

2016-05-04 8:52 GMT+02:00 Hugo Courtecuisse notifications@github.com:

**Comment by gustavi** [comment]
HS @SpaceFox serveur down, tu peux check (pas possible d'accèder au serveur d'où je suis) /HS

(pas moyen de te contacter facilement autrement)

**Comment by SpaceFox** [comment]
Ping OK, disk latency à 14 secondes… je crois qu'on ne peut qu'attendre (et
je n'ai normalement pas accès à la prod d'ici non plus).

2016-05-04 11:23 GMT+02:00 Laville Augustin notifications@github.com:

**Comment by SpaceFox** [comment]
Je confirme ne pas avoir accès à la prod.

**Comment by GerardPaligot** [comment]
Merci @gustavi
