### ISSUE TITLE
Notification permanante

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#3659]
Bonjour,

Depuis le forum, 

> Je me suis désabonné à un sujet (ne plus suivre) alors que j'avais une notification de se sujet.
> 
> Désormais j'ai en permanence 1 notification. Même si je me réabonne, elle ne disparaît plus ^^"
> Ce bug se combine également avec celui-ci [[v18] Date incorrecte dans les notifications](https://github.com/zestedesavoir/zds-site/issues/3628) .
> 
> D'ailleurs on peut voir ce bug comme l'opposé de celui-ci [Suivre un sujet, messages oubliés](https://github.com/zestedesavoir/zds-site/issues/3654) ».
> 
> Source: [ache](https://zestedesavoir.com/forums/sujet/6300/notification-permanante/)

**Comment by DevHugo** [comment]
Je rajoute que quand :
- Je créé un sujet avec l'utilisateur "User"
- J'ajoute un message avec l'utilisateur "Admin"
- Je clique sur le bouton " Ne plus suivre ce sujet" en tant qu'admin, l'api des notifications me renvoi une erreur 500.

C'est peut-être un bug différent ou le même, je sais pas, à investiguer.

Stacktrace:

```
Internal Server Error: /forums/sujet/editer/
Traceback (most recent call last):
  File "/home/hugo/dev/python/zdsenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hugo/dev/python/zdsenv/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/hugo/dev/python/zdsenv/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/hugo/dev/python/zdsenv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/hugo/dev/python/zdsenv/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/hugo/dev/python/zdsenv/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/hugo/dev/python/zds-site/zds/member/decorator.py", line 27, in _can_write_and_read_now
    return func(request, *args, **kwargs)
  File "/home/hugo/dev/python/zdsenv/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/hugo/dev/python/zdsenv/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/hugo/dev/python/zdsenv/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/hugo/dev/python/zdsenv/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/hugo/dev/python/zds-site/zds/forum/views.py", line 266, in dispatch
    return super(TopicEdit, self).dispatch(request, *args, **kwargs)
  File "/home/hugo/dev/python/zdsenv/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/hugo/dev/python/zds-site/zds/forum/views.py", line 323, in post
    return HttpResponse(json.dumps(response), content_type='application/json')
  File "/usr/lib64/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <TopicAnswerSubscription: <Abonnement du membre "admin" aux réponses au sujet #6>> is not JSON serializable
```

et la variable response vaut `<Abonnement du membre "admin" aux réponses au sujet #6>`.

**Comment by GerardPaligot** [comment]
> l'api des notifications me renvoi une erreur 500.

L'API ? Tu as la stacktrace de l'erreur 500 ?

**Comment by GerardPaligot** [comment]
De quelle API parles-tu ?

**Comment by DevHugo** [comment]
J'ai vu json + requêtte HTTP + 500, j'ai supposé qu'il avait une api mais c'est peut-être pas le cas.

**Comment by GerardPaligot** [comment]
Je confirme le bug de ton premier message par contre je n'ai aucune erreur 500 pour ton second message.

Es-tu certain d'être sur une bonne branche avec toutes les migrations qui vont bien et des données cohérentes ?

**Comment by DevHugo** [comment]
D’après ce que je vois de la correction, si quelqu'un se ré-inscrit et désinscrit au sujet, ça va bien supprimer l'ancienne notification ?

**Comment by GerardPaligot** [comment]
Ca va supprimer toutes les notifications attachées à ce contenu

**Comment by DevHugo** [comment]
Je comprend rien pour le deuxième souci, j'ai recréé une base depuis zéro et plus de souci … . Mais avec l'ancienne base de données, j'arrivais à le reproduire à chaque fois et j'avais toutes les migrations de faite. 

Tant mieux, c'est un faux positif et c'est cool.
