### ISSUE TITLE
API - Les adresses en PATCH ne semblent pas fonctionner

### ISSUE THREAD

**Issue by DevHugo** [zestedesavoir/zds-site#3765]
Bonjour, 

Quand j'effectue les requêtes suivantes en patch: 
- PATCH /api/membres/1/
- PATCH /api/mps/3/

J'ai l'erreur python suivante retourné par le serveur: 

```
Internal Server Error: /api/mps/3/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/generics.py", line 292, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 78, in partial_update
    return self.update(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 68, in update
    serializer = self.get_serializer(instance, data=request.data, partial=partial)
  File "/usr/lib/python2.7/site-packages/rest_framework/generics.py", line 111, in get_serializer
    return serializer_class(*args, **kwargs)
TypeError: 'NoneType' object is not callable
```

**Comment by GerardPaligot** [comment]
Toutà fait. L'API de Zeste de Savoir n'a jamais été compatible avec le verbe `PATCH`. Pire que ça, `PUT` permet la modification partielle.

**Comment by DevHugo** [comment]
Alors, il faut le supprimer de la documentation :) ! 

[https://zestedesavoir.com/api/#!/membres/Member_Detail_Api_PATCH](https://zestedesavoir.com/api/#!/membres/Member_Detail_Api_PATCH)

**Comment by GerardPaligot** [comment]
@DevHugo Pour bien faire, il faudrait supporter ce verbe mais je suis jamais arrivé à le supprimer de la documentation.

**Comment by DevHugo** [comment]
"[enabled_methods](https://github.com/zestedesavoir/zds-site/blob/1b066e0b57122a59b213550c8418e34d8f91abaf/zds/settings.py#L255)" dans la conf sert uniquement à afficher ou pas le bouton pour tester mais ne cache pas les méthodes précisés dans swagger.

Swagger se base sur les mixins quand il voit [UpdateAPIView](http://www.django-rest-framework.org/api-guide/generic-views/#updatemodelmixin), il comprend que tu veux faire du patch et du put. Comme indiqué dans la documentation de django-rest-framework.

Le workaround qu'on avait trouvé à l'époque était de précisé les méthodes http supportés comme cela:

``` python
class MemberDetailAPI(RetrieveUpdateAPIView):
    """
    Profile resource to display or update details of a member.
    """
    http_method_names = ['put']
```

Source:
- Issue sur [swagger](https://github.com/marcgibbons/django-rest-swagger/issues/73#issuecomment-227300878)
  - [StackOverflow](http://stackoverflow.com/questions/23639113/disable-a-method-in-a-viewset-django-rest-framework)
