### ISSUE TITLE
Problème d'accès à mon tutoriel

### ISSUE THREAD

**Issue by Bullesdair** [zestedesavoir/zds-site#3988]
Bonjour,

Mon compte est "Pincée d'air" j'ai écris le tutoriel : [https://zestedesavoir.com/tutoriels/1501/les-sources-du-droit-du-travail/](https://zestedesavoir.com/tutoriels/1501/les-sources-du-droit-du-travail/), qui vient juste d'être validé ce matin.

Quand j'accède à la page du tutoriel (lien ci-dessus) j'ai une erreur 500 (seulement quand je suis connecté à mon compte). Je ne peux pas accéder à mon tutoriel. 

De plus j'ai 3 notifications qui me donne une erreur redirige vers mon tutoriel ([https://zestedesavoir.com/tutoriels/1501/les-sources-du-droit-du-travail/](https://zestedesavoir.com/tutoriels/1501/les-sources-du-droit-du-travail/)).

![](http://i.imgur.com/RQpl1TM.png)

Je ne sais pas si elles sont en double/triple, parce qu'il me semble qu'arius a fais 2-3 manip pour valider le tutoriel.

Donc quand j'accède à mon tutoriel j'ai : 

![](http://i.imgur.com/mObS5ot.png)

J'ai regardé l'header de la réponse le status Code est "200 OK", la date est : `Date:Sat, 19 Nov 2016 11:43:38 GMT`.

@vhf m'a donné cette ligne de logs me concernant : 

    .... - - [19/Nov/2016:11:09:45 +0100] "GET /tutoriels/1501/les-sources-du-droit-du-travail/ HTTP/2.0" 200 6482 "https://zestedesavoir.com/notifications/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0"

**Comment by vhf** [comment]
Stack trace:

```
[ERROR] -- 2016-11-19 11:08:48,015 -- __init__ : Internal Server Error: /tutoriels/1501/les-sources-du-droit-du-trav
ail/
Traceback (most recent call last):
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/zds/zds-site/zds/tutorialv2/mixins.py", line 414, in get
    context = self.get_context_data(object=self.object)
  File "/opt/zds/zds-site/zds/tutorialv2/views/views_published.py", line 133, in get_context_data
    sender=self.object.__class__, instance=self.object, user=self.request.user, target=PublishableContent)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/opt/zds/zds-site/zds/notification/receivers.py", line 105, in mark_content_reactions_read
    subscription.mark_notification_read(content=content)
  File "/opt/zds/zds-site/zds/notification/models.py", line 212, in mark_notification_read
    object_id=content.pk, is_read=False)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one Notification -- it returned 2!
[ERROR] -- 2016-11-19 11:09:16,183 -- __init__ : Internal Server Error: /tutoriels/1501/les-sources-du-droit-du-trav
ail/
Traceback (most recent call last):
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/zds/zds-site/zds/tutorialv2/mixins.py", line 414, in get
    context = self.get_context_data(object=self.object)
  File "/opt/zds/zds-site/zds/tutorialv2/views/views_published.py", line 133, in get_context_data
    sender=self.object.__class__, instance=self.object, user=self.request.user, target=PublishableContent)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/opt/zds/zds-site/zds/notification/receivers.py", line 105, in mark_content_reactions_read
    subscription.mark_notification_read(content=content)
  File "/opt/zds/zds-site/zds/notification/models.py", line 212, in mark_notification_read
    object_id=content.pk, is_read=False)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one Notification -- it returned 3!
```

Notez que cette stack trace provient des logs serveur, elle ne parvient pas à Sentry, probablement à cause du HTTP200 au lieu du HTTP500.

Je pense que ce sera corrigé par la PR https://github.com/zestedesavoir/zds-site/pull/3954

**Comment by pierre-24** [comment]
À priori ok :)
