### ISSUE TITLE
Voir un message où on est pingé donne une 500

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#4192]
```
[ERROR] -- 2017-02-11 14:11:25,507 -- base : Internal Server Error: /forums/sujet/7920/salidou/
Traceback (most recent call last):
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/zds/zds-site/zds/forum/views.py", line 152, in get
    return super(TopicPostsListView, self).get(request, *args, **kwargs)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/opt/zds/zds-site/zds/forum/views.py", line 186, in get_context_data
    signals.content_read.send(sender=post.__class__, instance=post, user=self.request.user)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/opt/zds/zds-site/zds/notification/receivers.py", line 145, in mark_comment_read
    subscription.mark_notification_read(comment)
  File "/opt/zds/zds-site/zds/notification/models.py", line 226, in mark_notification_read
    LOG.warning('%s notifications were find for %s/%s', len(notifications), content.type, content.title)
AttributeError: 'Post' object has no attribute 'type'
```

Probablement facile à réparer.

**Comment by vhf** [comment]
Super facile à régler : 

```diff
diff --git a/zds/notification/models.py b/zds/notification/models.py
index a836f4e..1165654 100644
--- a/zds/notification/models.py
+++ b/zds/notification/models.py
@@ -223,7 +223,7 @@ class MultipleNotificationsMixin(object):
             LOG.debug('nothing to mark as read')
             return
         elif len(notifications) > 1:
-            LOG.warning('%s notifications were find for %s/%s', len(notifications), content.type, content.title)
+            # LOG.warning('%s notifications were find for %s/%s', len(notifications), content.type, content.title)
             for notif in notifications[1:]:
                 notif.delete()
```

Du coup si quelqu'un sait réparer plus proprement que ça, volontiers. J'ai hotfixé la beta.

En profiter pour corriger le logging svp : `were found`, pas `were find`
