### ISSUE TITLE
BASE_DIR devrait être un pathlib.Path

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zds-site#4744]
C’est [complètement possible](https://github.com/django/djangoproject.com/blob/master/djangoproject/settings/common.py#L10), c’est pas difficile à faire (c’est juste long) et ça enlèverai pleins de `os.path.join` tout moches.

**Comment by rezemika** [comment]
J'ai tenté de mon côté, mais j'obtiens une erreur que je n'arrive pas à résoudre et qui vient apparemment causée par `django.utils.autoreload`.

```
Traceback (most recent call last):
  File "manage.py", line 47, in <module>
    execute_from_command_line(sys.argv)
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 58, in execute
    super(Command, self).execute(*args, **options)
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 97, in handle
    self.run(**options)
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 106, in run
    autoreload.main(self.inner_run, None, options)
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/utils/autoreload.py", line 333, in main
    reloader(wrapped_main_func, args, kwargs)
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/utils/autoreload.py", line 299, in python_reloader
    reloader_thread()
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/utils/autoreload.py", line 275, in reloader_thread
    change = fn()
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/utils/autoreload.py", line 204, in code_changed
    for filename in gen_filenames():
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/utils/autoreload.py", line 114, in gen_filenames
    basedirs = [os.path.abspath(basedir) for basedir in basedirs
  File "/home/rezemika/zds/venv3.4/lib/python3.4/site-packages/django/utils/autoreload.py", line 115, in <listcomp>
    if os.path.isdir(basedir)]
  File "/home/rezemika/zds/venv3.4/lib/python3.4/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: argument should be string, bytes or integer, not PosixPath
```

Est-ce qu'il y a un moyen de contourner ça ?

**Comment by Arnaud-D** [comment]
Salut,

Le ticket est tagué comme facile, mais ce n'est pas si facile que ça. Je dis ça en connaissance de cause, parce que j'ai tenté de mon côté et j'ai eu un peu les mêmes problèmes, qui ne sont pas si évidents à résoudre.

Notamment, il y a plein d'endroits dans le code où on utilise le `BASE_DIR` indirectement, et où les fonctions attendent un chemin sous forme de `string` et pas de `PosixPath`. Du coup, il faut convertir explicitement à beaucoup d'endroits.

Je ne sais pas si cela va t'aiguiller, mais essaie de regarder attentivement dans `settings/django.py`. J'ai dû tenter des trucs du type `STATIC_ROOT = str(BASE_DIR.joinpath('static'))` pour éviter la propagation de `PosixPath` jusqu'au fin fond de Python. Aucune idée si c'est une bonne façon ou pas par contre.

**Comment by rezemika** [comment]
> Je ne sais pas si cela va t'aiguiller, mais essaie de regarder attentivement dans settings/django.py. J'ai dû tenter des trucs du type STATIC_ROOT = str(BASE_DIR.joinpath('static')) pour éviter la propagation de PosixPath jusqu'au fin fond de Python. Aucune idée si c'est une bonne façon ou pas par contre.

Han merci, j'avais pas fait gaffe à ça ! J'ai fais des `str(BASE_DIR / 'contents-private')` et ça marche.

Maintenant, du courage, plus que 300 tests unitaires à corriger (edit : un peu moins de 200 maintenant, mais j'ai une segfault, je vais faire une PR) ! :D
