### ISSUE TITLE
Cycle d'import dans les settings en mode production

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#4867]
Lors du chargement des settings en mode production, la version reportée à Sentry est calculée à la volée par le *context processor* `get_git_version`, qui lui-même utilise le settings `BASE_DIR`

https://github.com/zestedesavoir/zds-site/blob/5eebddc22e86a8521076dbac8e64ed5e8b7c88e4/zds/settings/prod.py#L81-L84

https://github.com/zestedesavoir/zds-site/blob/5eebddc22e86a8521076dbac8e64ed5e8b7c88e4/zds/utils/context_processor.py#L9-L25

Sauf qu'à ce moment là, les settings ne sont pas encore chargés, et `get_git_version` va donc être lancé sur le `CWD`.

Ça pose problème parce que ça impose de lancer l'appli depuis le bon dossier (pour le `manage.py` aussi) pour que Sentry renvoie la bonne version, mais aussi que le `manage.py` plante lorsqu'on essaie de le lancer depuis un dossier où l'utilisateur `zds` n'a pas les accès.

```
root@zdsprod1:~# sudo -E -u zds /opt/zds/virtualenv/bin/python /opt/zds/app/manage.py
Traceback (most recent call last):
  File "/opt/zds/app/manage.py", line 47, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/zds/app/zds/settings/prod.py", line 1, in <module>
    from zds.utils.context_processor import get_git_version
  File "/opt/zds/app/zds/utils/context_processor.py", line 8, in <module>
    from git import Repo
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/git/__init__.py", line 45, in <module>
    from git.repo import Repo               # @NoMove @IgnorePep8
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/git/repo/__init__.py", line 4, in <module>
    from .base import *
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/git/repo/base.py", line 31, in <module>
    from git.remote import Remote, add_progress, to_progress_instance
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/git/remote.py", line 190, in <module>
    class FetchInfo(object):
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/git/remote.py", line 219, in FetchInfo
    v = Git().version_info[:2]
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/git/cmd.py", line 461, in version_info
    return self._version_info
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/git/cmd.py", line 424, in __getattr__
    return LazyMixin.__getattr__(self, name)
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/gitdb/util.py", line 256, in __getattr__
    self._set_cache_(attr)
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/git/cmd.py", line 444, in _set_cache_
    version_numbers = self._call_process('version').split(' ')[2]
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/git/cmd.py", line 877, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/opt/zds/virtualenv/lib/python3.5/site-packages/git/cmd.py", line 599, in execute
    **subprocess_kwargs
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

Je pense que ça peut intéresser @motet-a.

**Comment by artragis** [comment]
c'(est fixé ça; non? @sandhose @Situphen ?

**Comment by Situphen** [comment]
J'ai regardé le code et oui ça m'a l'air corrigé !
