### ISSUE TITLE
Compatibilité Python 3.7

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/zds-site#5305]
Visiblement sous ArchLinux avec Python 3.7 l'installation est impossible.

Voici un exemple d'erreurs que j'ai : 

```
Collecting django-munin==0.2.1 (from -r requirements.txt (line 11))
Exception:
Traceback (most recent call last):
  File "/home/gustavi/code/zds/venv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/home/gustavi/code/zds/venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/home/gustavi/code/zds/venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/gustavi/code/zds/venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/gustavi/code/zds/venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/home/gustavi/code/zds/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 334, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/home/gustavi/code/zds/venv/lib/python3.7/site-packages/pip/_internal/download.py", line 865, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/home/gustavi/code/zds/venv/lib/python3.7/site-packages/pip/_internal/download.py", line 763, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/home/gustavi/code/zds/venv/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 626, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/home/gustavi/code/zds/venv/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 503, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib64/python3.7/zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "/usr/lib64/python3.7/zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Les paquets concernés que j'ai identifié : 

- [x] django-munin (j'ai ouvert un ticket à ce sujet d'ailleurs)
- [x] django-cors-middleware
- [x] watchdog

Pour le moment je ne cherche pas à creuser plus, j'ai utilisé 3.6 et tout fonctionne bien, rien d'urgent.

**Comment by artragis** [comment]
- pour watchdog je pense que dans la prochaine itération, je vais le virer.
- pour django-cors-middleware faudrait simplement que j'ai de quoi publier la dernière version du truc : au départ c'est toi qui t'en occupais, mais y'a pas de maintenance qui a été faite depuis un baille
- pour django-munin, je regarde pourquoi ça fait ça demain

**Comment by gustavi** [comment]
Pour cors je te contacte en privé pour voir qui a les accès.

**Comment by gustavi** [comment]
Note : je vais installer une Arch clean ce week-end pour tester et confirmer ce comportement.

**Comment by artragis** [comment]
@gustavi faut qu'on se voit pour ce qui concerne cors-middleware

**Comment by gustavi** [comment]
@artragis ping moi sur Discord un soir un ce week-end.

**Comment by Situphen** [comment]
@gustavi Tu as réessayé avec Python 3.7 ? artragis et moi on arrive bien à installer tous les paquets Pip.

**Comment by gustavi** [comment]
Visiblement sur une Debian 10 je n'ai plus le problème.
