### ISSUE TITLE
Connexion via les réseaux sociaux impossible

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5560]
Connexion via les réseaux sociaux impossible.

```
Traceback (most recent call last):
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_django/views.py", line 33, in complete
    *args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_core/actions.py", line 43, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_core/utils.py", line 251, in wrapper
    return func(*args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_core/backends/oauth.py", line 405, in auth_complete
    *args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_core/utils.py", line 251, in wrapper
    return func(*args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_core/backends/oauth.py", line 416, in do_auth
    return self.strategy.authenticate(*args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_django/strategy.py", line 107, in authenticate
    return authenticate(*args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_core/backends/base.py", line 80, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_core/backends/base.py", line 83, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_core/backends/base.py", line 112, in run_pipeline
    func = module_member(name)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_core/utils.py", line 62, in module_member
    module = import_module(mod)
  File "/opt/zds/virtualenv/lib/python3.7/site-packages/social_core/utils.py", line 56, in import_module
    __import__(name)
ModuleNotFoundError: No module named 'social'
```

**Comment by Situphen** [comment]
Corrigé manuellement sur le serveur, donc non bloquant.

**Comment by A-312** [comment]
On ne peut pas ajouter de meilleurs tests notamment avec selenium ? Ou c'est impossible de tester la connexion ?

**Comment by Situphen** [comment]
Impossible de tester la connexion car il faudrait les clés secrètes OAuth je pense.

**Comment by A-312** [comment]
Même dans travis ?

**Comment by Situphen** [comment]
L'erreur ne se produit qu'après tentative de connexion avec un compte Google ou Facebook, donc il faut un compte et une clé secrète valide de leur côté, sinon on n'attendra jamais le moment où il peut y avoir l'erreur je pense.
