### ISSUE TITLE
Problème de fixture lors de l'installation sur Windows

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zds-site#5579]
Comment puis je régler le soucis ?

```
Nombres de membres à créer : 10
 User 10/10
Fait en 3.2510011196136475 sec
Nombres de staffs à créer : 3
 Staff 3/3
Fait en 1.860856056213379 sec
Nombres de galéries à créer par utilisateur: 1
Nombres d'images à créer par gallerie: 3
 User 60/60     Gallery 1/1     Image 3/3
Fait en 7.7132580280303955 sec
Nombres de catégories de forum à créer : 4
Traceback (most recent call last):
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: forum_category.slug

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 60, in <module>
    execute_from_command_line(sys.argv)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "E:\GitHub\zds-site\zds\utils\management\commands\load_fixtures.py", line 636, in handle
    zds_module.callback(self, size, fake, *zds_module.extra_args, root=default_root)
  File "E:\GitHub\zds-site\zds\utils\management\commands\load_fixtures.py", line 148, in load_categories_forum
    cat = CategoryFactory(position=i + 1)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\factory\base.py", line 69, in __call__
    return cls.create(**kwargs)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\factory\base.py", line 623, in create
    return cls._generate(True, attrs)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\factory\base.py", line 548, in _generate
    obj = cls._prepare(create, **attrs)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\factory\base.py", line 523, in _prepare
    return cls._create(model_class, *args, **kwargs)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\factory\django.py", line 181, in _create
    return manager.create(*args, **kwargs)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\models\query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\models\base.py", line 740, in save
    self.save_base(using=using, force_insert=force_insert,
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\models\base.py", line 777, in save_base
    updated = self._save_table(
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\models\base.py", line 907, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\models\sql\compiler.py", line 1368, in execute_sql
    cursor.execute(sql, params)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\GitHub\zds-site\zdsenv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: forum_category.slug

error: missing required argument `name|id'
```

**Comment by artragis** [comment]
C'est pas lié à windows et c'est aléatoire.

**Comment by A-312** [comment]
> C'est pas lié à windows et c'est aléatoire.

Je l'ai à chaque fois :/

**Comment by A-312** [comment]
Les factories ne vérifie pas si le slug existe deja

![image](https://user-images.githubusercontent.com/18501150/72687654-47de2100-3b00-11ea-89e0-44b124b5ad69.png)
![image](https://user-images.githubusercontent.com/18501150/72687655-4a407b00-3b00-11ea-93be-1a85aa5e76ad.png)

**Comment by A-312** [comment]
J'avais oublié de supprimer base.db (j'étais sur de l'avoir fait, mais il était en fichier caché)...
