### ISSUE TITLE
[Dev] Impossible de lancer le serveur sous Ubuntu 18.04

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zds-site#5667]
Quand j'essaie de lancer le serveur avec `make run-back` sur `upstream/dev` avec toutes les dépendances à jours, j'ai cette erreur : 

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/situphen/Code/zds-site/zdsenv/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/situphen/Code/zds-site/zdsenv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/situphen/Code/zds-site/zdsenv/lib/python3.6/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/home/situphen/Code/zds-site/zdsenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/situphen/Code/zds-site/zdsenv/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/situphen/Code/zds-site/zdsenv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/situphen/Code/zds-site/zdsenv/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/situphen/Code/zds-site/zdsenv/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/situphen/Code/zds-site/zds/member/models.py", line 16, in <module>
    from zds.tutorialv2.models.database import PublishableContent, PublishedContent
  File "/home/situphen/Code/zds-site/zds/tutorialv2/models/database.py", line 24, in <module>
    from git import Repo, BadObject
  File "/home/situphen/Code/zds-site/zdsenv/lib/python3.6/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/home/situphen/Code/zds-site/zdsenv/lib/python3.6/site-packages/git/exc.py", line 8, in <module>
    from gitdb.exc import *     # NOQA @UnusedWildImport skipcq: PYL-W0401, PYL-W0614
ModuleNotFoundError: No module named 'gitdb.exc'
```

Ça me semble lié à l'introdution de `gitdb` dans le `requirements.txt` par #5390, @A-312 peux-tu me dire pourquoi cette dépendance est nécessaire ? :)

**Comment by A-312** [comment]
Parce que sous linux/windows cette dépendance manquait et entraînait le plantage de l'installation (voir discord)

**Comment by A-312** [comment]
![image](https://user-images.githubusercontent.com/18501150/77449792-b4bcb280-6df2-11ea-9aff-4d9edd3d9362.png)

je croyais qu'il y avait aussi un cas sur linux, impossible de le retrouver

**Comment by A-312** [comment]
https://github.com/zestedesavoir/zds-site/issues/5640
