### ISSUE TITLE
PRE-COMMIT empêche de commit son travail

### ISSUE THREAD

**Issue by GlaceCoding** [zestedesavoir/zds-site#6279]
Bonjour, je faisais mes modifications en local et quand j'essaye de commit avec `git commit -m "mon message"` j'ai un message d'erreur que je sois dans ou en dehors de l'environnement, je suis sur `Ubuntu 20.04.4 LTS`.

Pour fix le problème, j'ai fais `rm .git/hooks/pre-commit`.

Une fois que je vais push en origin, je vais recloner le repository, en espérant corriger le problème comme ça.

```
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/glacecoding/Documents/zds-site/zdsenv/bin/python3', '-mvirtualenv', '/home/glacecoding/.cache/pre-commit/repoedlnarw4/py_env-python3')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to build image setuptools, pip because:
    Traceback (most recent call last):
      File "/home/glacecoding/Documents/zds-site/zdsenv/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 57, in _install
        installer.install(creator.interpreter.version_info)
      File "/home/glacecoding/Documents/zds-site/zdsenv/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 35, in install
        self._uninstall_previous_version()
      File "/home/glacecoding/Documents/zds-site/zdsenv/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 151, in _uninstall_previous_version
        dist_name = self._dist_info.stem.split("-")[0]
      File "/home/glacecoding/Documents/zds-site/zdsenv/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 115, in _dist_info
        raise RuntimeError(msg)  # pragma: no cover
    RuntimeError: no .dist-info at /home/glacecoding/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-61.0.0-py3-none-any, has setuptools, pkg_resources, distutils-precedence.pth, _distutils_hack
    
    Traceback (most recent call last):
      File "/home/glacecoding/Documents/zds-site/zdsenv/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 57, in _install
        installer.install(creator.interpreter.version_info)
      File "/home/glacecoding/Documents/zds-site/zdsenv/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 35, in install
        self._uninstall_previous_version()
      File "/home/glacecoding/Documents/zds-site/zdsenv/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 151, in _uninstall_previous_version
        dist_name = self._dist_info.stem.split("-")[0]
      File "/home/glacecoding/Documents/zds-site/zdsenv/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 115, in _dist_info
        raise RuntimeError(msg)  # pragma: no cover
    RuntimeError: no .dist-info at /home/glacecoding/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-22.0.4-py3-none-any, has pip
    
    
stderr: (none)
Check the log at /home/glacecoding/.cache/pre-commit/pre-commit.log
```

**Comment by Situphen** [comment]
Tiens c'est étonnant j'utilise la même version d'Ubuntu et je n'ai jamais eu ce soucis avec Pre-Commit.

J'ai trouvé ce ticket qui parle de la même erreur, bien que je suis assez dubitatif concernant l'explication donnée https://github.com/pypa/virtualenv/issues/1971

Si tu as besoin de temporairement désactiver Pre-Commit, tu peux ajouter `--no-verify` à la commande `git commit`.

**Comment by GlaceCoding** [comment]
Fonctionne correctement après réinstallation (j'ai fais un rollback de ma VM avant installation) 👍🏻
