### ISSUE TITLE
Erreur dans /membres/?q=... via AJAX

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/zds-site#798]
Suite à l'ajout de la réponse sous forme JSON de `/membres/` ( #677 ), le GET de cette page avec le header `X-Requestes-With: XMLHttpRequest` plante, dû au fait que la lib JSON n'est pas importé dans le fichier `zds/membres/view.py`

``` bash
[07/Jun/2014 14:30:49] "GET /membres/?q=a HTTP/1.1" 500 15042
Internal Server Error: /membres/
Traceback (most recent call last):
  File "~/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "zds/member/decorator.py", line 21, in _can_read_now
    return func(request, *args, **kwargs)
  File "zds/member/views.py", line 55, in index
    data = json.dumps(results)
NameError: global name 'json' is not defined
```

**Comment by sandhose** [comment]
Oups: cela a été corrigé il y a un moment, ma branche sur laquelle je bosse était pas tout à fait à jour, mais il y a une erreur à cause de la variable `mimetype` non déclarée

``` bash
Traceback (most recent call last):
  File "~/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "zds/member/views.py", line 58, in index
    return HttpResponse(data, mimetype)
NameError: global name 'mimetype' is not defined
```
